name: All Contributors
on:
  schedule:
    - cron: "0 0 * * 1" # every Monday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: All contributors across repositories
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.contributors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_contributors: yes
          plugin_contributors_contributions: yes
