name: 🧠 Chess Stats Action

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with chess.com stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Chess.com Stats
        uses: Stanford-mcfly/chess-stats-action@main
        with:
          CHESS_USERNAME: vijaykg  # Replace with your Chess.com username
