name: GitHub Contribution Calendar

on:
  schedule:
    - cron: "0 0 * * 0"  # runs weekly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

